# pull official base image
FROM node:12.18

# set working directory
WORKDIR /usr/src/app


# add `/app/node_modules/.bin` to $PATH
ENV PATH /app/node_modules/.bin:$PATH

# install app dependencies
COPY package*.json /usr/src/app/
RUN npm install

# build gentle

COPY public/ /usr/src/app/public
COPY src/ /usr/src/app/src

RUN npm run-script build

# add node app and environment variables

COPY app.js /usr/src/app
COPY .env /usr/src/app

# start app
CMD ["node", "app.js"]